### ISSUE TITLE
че за интегер? он же лонг

### ISSUE THREAD

**Issue by idfedorov09** [idfedorov09/SofFYS#5]
че за интегер? он же лонг

_Originally posted by @idfedorov09 in https://github.com/idfedorov09/SofFYS/pull/4#discussion_r1335165954_

**Comment by IgorL123** [comment]
хз

**Comment by IgorL123** [comment]
with mlflow.start_run():

**Comment by idfedorov09** [comment]
@ThePrax12  чекни тут https://github.com/idfedorov09/SofFYS/blob/babuins/src/main/java/ru/idfedorov09/telegram/bot/data/model/Team.kt

**Comment by ThePrax12** [comment]
ИСПРАВИЛ
