### ISSUE TITLE
1. Где номер проблемы?

### ISSUE THREAD

**Issue by idfedorov09** [idfedorov09/SofFYS#7]
Ку
1. Где номер проблемы?
2. Не хочешь сделать текст кабибабельным? Это можно сделать [вот так](https://github.com/idfedorov09/ConsultationsPollingBot/blob/58e9648e6e482a1085d3f2bae3c8f2df8bbf90e4/src/main/java/ru/idfedorov09/telegram/bot/fetcher/AdminCommandsFetcher.kt#L106)

_Originally posted by @idfedorov09 in https://github.com/idfedorov09/SofFYS/pull/4#discussion_r1335168488_

**Comment by ThePrax12** [comment]
Исправил вроде всё
