### ISSUE TITLE
Во-первых, ты будешь кидать по 3 сообщения в ответ на запрос? такое себе

### ISSUE THREAD

**Issue by idfedorov09** [idfedorov09/SofFYS#8]
Во-первых, ты будешь кидать по 3 сообщения в ответ на запрос? такое себе
Во-вторых, "i" тебе будет писать просто `i`, что не ожидается, ожидается номер
В-третьих, на котлине лучше писать что-то такое
```kotlin
"$i. '${problem.category} ${problem.cost}'"
```
В-четвертых, кажется, будто стоит указывать сколько попыток осталось
Примерно так:
`1. Беляши 1100 (0/2)`
`1. Пайплайны 200 (1/2)`
Оставь TODO с инфой об этом, так как щас вроде нельзя такое сделать из-за бд

_Originally posted by @idfedorov09 in https://github.com/idfedorov09/SofFYS/pull/4#discussion_r1335171768_

**Comment by ThePrax12** [comment]
Исправил. Добавил вариант на случай отсутствия задач в пуле.
